- name: create cidr for use in unbound cfg
  import_tasks: get_cidr.yml

- name: install and configure unbound
  import_tasks: install_unbound.yml

- name: download blacklist
  import_tasks: download_blacklist.yml

- name: send local static dns overrides
  import_tasks: local_dns.yml



